name: test feature branch

on:
  push:
    branches:
      - 'feature/**/*'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: install
        run: npm ci

      - name: format
        run: npm run format

      - name: test
        run: npm run test
